language: java

## Can I do this when running on multiple OSes?
# sudo: required
# dist: trusty

script: ./.travis-build.sh

os:
  - linux
  - osx
# Cannot switch JDK version on MacOSX yet: https://github.com/travis-ci/travis-ci/issues/2317
# jdk:
#   - oraclejdk8
# #  - oraclejdk7
#   - openjdk7
